
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'Q\x0cr\xd1\xc7\xed\xf1+\x164.x\xdd;\xe3K'
    
_lr_action_items = {'NODE':([4,9,16,17,23,28,50,52,53,56,63,64,65,66,],[5,5,19,21,5,19,59,60,61,62,67,68,69,70,]),'TASKS':([0,10,30,],[2,2,2,]),'END':([5,18,19,21,26,48,71,72,73,74,],[10,10,30,-26,10,58,76,78,80,82,]),'OPTION':([5,18,19,21,26,],[8,8,26,-26,26,]),'SOD':([10,15,20,25,27,29,30,31,37,38,39,41,42,47,49,51,54,55,57,58,76,78,80,82,83,84,85,86,],[-32,-33,32,-19,-22,-21,32,-3,-30,-27,-28,-20,-34,-29,-6,-7,-5,-4,-31,32,-12,-14,-10,-8,-13,-15,-11,-9,]),'USERS':([6,7,10,11,14,15,20,22,24,25,27,29,30,31,36,37,38,39,41,42,47,49,51,54,55,57,76,78,80,82,83,84,85,86,],[12,-16,-32,-18,-17,-33,-2,-25,-23,-19,-22,-21,-32,-3,-24,-30,-27,-28,-20,-34,-29,-6,-7,-5,-4,-31,-12,-14,-10,-8,-13,-15,-11,-9,]),'RPAREN':([67,68,69,70,],[71,72,73,74,]),'COLON':([2,8,12,26,32,33,34,35,],[4,13,16,40,43,44,45,46,]),'ALLOCATE':([40,],[48,]),'LPAREN':([43,44,45,46,75,77,79,81,],[50,52,53,56,50,52,53,56,]),'SENIORITY':([10,15,20,25,27,29,30,31,37,38,39,41,42,47,49,51,54,55,57,58,76,78,80,82,83,84,85,86,],[-32,-33,33,-19,-22,-21,33,-3,-30,-27,-28,-20,-34,-29,-6,-7,-5,-4,-31,33,-12,-14,-10,-8,-13,-15,-11,-9,]),'COMMA':([5,18,19,21,26,59,60,61,62,71,72,73,74,],[9,23,28,-26,39,63,64,65,66,75,77,79,81,]),'BEFORE':([10,15,20,25,27,29,30,31,37,38,39,41,42,47,49,51,54,55,57,58,76,78,80,82,83,84,85,86,],[-32,-33,35,-19,-22,-21,35,-3,-30,-27,-28,-20,-34,-29,-6,-7,-5,-4,-31,35,-12,-14,-10,-8,-13,-15,-11,-9,]),'BOD':([10,15,20,25,27,29,30,31,37,38,39,41,42,47,49,51,54,55,57,58,76,78,80,82,83,84,85,86,],[-32,-33,34,-19,-22,-21,34,-3,-30,-27,-28,-20,-34,-29,-6,-7,-5,-4,-31,34,-12,-14,-10,-8,-13,-15,-11,-9,]),'EQ':([13,],[17,]),'$end':([1,3,10,15,20,25,27,29,30,31,37,38,39,41,42,47,49,51,54,55,57,76,78,80,82,83,84,85,86,],[-1,0,-32,-33,-2,-19,-22,-21,-32,-3,-30,-27,-28,-20,-34,-29,-6,-7,-5,-4,-31,-12,-14,-10,-8,-13,-15,-11,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'begin':([0,10,30,],[1,15,15,]),'end':([5,18,19,26,],[7,22,25,37,]),'task_node':([4,9,23,],[6,14,36,]),'rules':([20,30,58,],[31,42,42,]),'user_node':([16,28,],[20,41,]),'sod_task_node_pair':([43,75,],[49,83,]),'user_node_pair':([44,77,],[51,84,]),'end_rule':([19,48,],[27,57,]),'users_global_option':([40,],[47,]),'before_task_node_pair':([46,81,],[55,86,]),'user_option':([19,26,],[29,38,]),'prog':([0,],[3,]),'bod_task_node_pair':([45,79,],[54,85,]),'task_option':([5,18,],[11,24,]),'op':([13,],[18,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> begin','prog',1,'p_prog','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',40),
  ('begin -> TASKS COLON task_node USERS COLON user_node','begin',6,'p_begin','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',46),
  ('begin -> TASKS COLON task_node USERS COLON user_node rules','begin',7,'p_begin','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',47),
  ('rules -> BEFORE COLON before_task_node_pair','rules',3,'p_rules','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',69),
  ('rules -> BOD COLON bod_task_node_pair','rules',3,'p_rules','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',70),
  ('rules -> SOD COLON sod_task_node_pair','rules',3,'p_rules','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',71),
  ('rules -> SENIORITY COLON user_node_pair','rules',3,'p_rules','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',72),
  ('before_task_node_pair -> LPAREN NODE COMMA NODE RPAREN END','before_task_node_pair',6,'p_before_task_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',77),
  ('before_task_node_pair -> LPAREN NODE COMMA NODE RPAREN COMMA before_task_node_pair','before_task_node_pair',7,'p_before_task_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',78),
  ('bod_task_node_pair -> LPAREN NODE COMMA NODE RPAREN END','bod_task_node_pair',6,'p_bod_task_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',85),
  ('bod_task_node_pair -> LPAREN NODE COMMA NODE RPAREN COMMA bod_task_node_pair','bod_task_node_pair',7,'p_bod_task_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',86),
  ('sod_task_node_pair -> LPAREN NODE COMMA NODE RPAREN END','sod_task_node_pair',6,'p_sod_task_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',92),
  ('sod_task_node_pair -> LPAREN NODE COMMA NODE RPAREN COMMA sod_task_node_pair','sod_task_node_pair',7,'p_sod_task_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',93),
  ('user_node_pair -> LPAREN NODE COMMA NODE RPAREN END','user_node_pair',6,'p_user_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',101),
  ('user_node_pair -> LPAREN NODE COMMA NODE RPAREN COMMA user_node_pair','user_node_pair',7,'p_user_pair','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',102),
  ('task_node -> NODE end','task_node',2,'p_task_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',109),
  ('task_node -> NODE COMMA task_node','task_node',3,'p_task_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',110),
  ('task_node -> NODE task_option','task_node',2,'p_task_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',111),
  ('user_node -> NODE end','user_node',2,'p_user_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',124),
  ('user_node -> NODE COMMA user_node','user_node',3,'p_user_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',125),
  ('user_node -> NODE user_option','user_node',2,'p_user_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',126),
  ('user_node -> NODE end_rule','user_node',2,'p_user_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',127),
  ('task_option -> OPTION COLON op task_option','task_option',4,'p_task_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',134),
  ('task_option -> OPTION COLON op COMMA task_node','task_option',5,'p_task_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',135),
  ('task_option -> OPTION COLON op end','task_option',4,'p_task_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',136),
  ('op -> EQ NODE','op',2,'p_op','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',149),
  ('user_option -> OPTION user_option','user_option',2,'p_user_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',154),
  ('user_option -> OPTION COMMA','user_option',2,'p_user_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',155),
  ('user_option -> OPTION COLON users_global_option','user_option',3,'p_user_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',156),
  ('user_option -> OPTION end','user_option',2,'p_user_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',157),
  ('users_global_option -> ALLOCATE end_rule','users_global_option',2,'p_users_global_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',162),
  ('end -> END','end',1,'p_end','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',170),
  ('end -> END begin','end',2,'p_end','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',171),
  ('end_rule -> END rules','end_rule',2,'p_end_rule','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/p_c.py',176),
]
