
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf2B\xd04\x9f\x8e\xef\xb6dd\n$\xdd\x82\xba\xc5'
    
_lr_action_items = {'NODE':([4,5,11,17,],[7,7,7,7,]),'OPTION':([7,13,],[13,13,]),'TASKS':([0,12,],[2,2,]),'END':([7,13,],[12,12,]),'USERS':([0,12,],[3,3,]),'COLON':([2,3,],[4,5,]),'COMMA':([7,13,],[11,17,]),'$end':([1,6,8,9,10,12,14,15,16,18,19,],[0,-1,-2,-3,-5,-9,-4,-10,-8,-6,-7,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'node':([4,5,11,17,],[6,8,14,19,]),'begin':([0,12,],[1,15,]),'end':([7,13,],[9,16,]),'option':([7,13,],[10,18,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> begin","S'",1,None,None,None),
  ('begin -> TASKS COLON node','begin',3,'p_begin','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',12),
  ('begin -> USERS COLON node','begin',3,'p_begin','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',13),
  ('node -> NODE end','node',2,'p_task_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',24),
  ('node -> NODE COMMA node','node',3,'p_task_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',25),
  ('node -> NODE option','node',2,'p_task_node','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',26),
  ('option -> OPTION option','option',2,'p_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',30),
  ('option -> OPTION COMMA node','option',3,'p_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',31),
  ('option -> OPTION end','option',2,'p_option','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',32),
  ('end -> END','end',1,'p_end','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',36),
  ('end -> END begin','end',2,'p_end','/home/joanna/Third_Year/Individual_Project/Business_Management_Processes/src/parser/Parser.py',37),
]
